# Generated by Django 4.0.4 on 2022-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_alter_contact_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
