# Generated by Django 4.0.4 on 2022-05-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_remove_contact_nom_remove_contact_prenom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='telephone',
        ),
    ]
