# Generated by Django 4.0.4 on 2022-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_rename_email_contact_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
