# Generated by Django 4.0.4 on 2022-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_remove_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
