# Generated by Django 4.0.4 on 2022-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0006_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
