# Generated by Django 4.0.4 on 2022-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0007_remove_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
